### ISSUE TITLE
Authorship verification task 2020 - baselines 

### ISSUE THREAD

**Issue by boenninghoff** [pan-webis-de/pan-code#1]
Hi PAN organizers, 

thank you for sharing the baseline methods!

I just would like to report some issues I found, when tried to train both methods on my own train/dev set split (finally it worked):

Baseline "pan20-verif-baseline.py": 

- The computation of the cosine similarity in lines 63/64 can lead to NaN values (at least for two documents). Adding a small value to the denominator was helpful.

Baseline "pan20-authorship-verification-baseline-compressor.py":

- In function "def train_data()", the list "data" that should contain all features, remains empty. I fixed it with "data.append(D)". 

- In the function "def train_model()", the function "LogisticRegression()" does not support a list of lists. I fixed it with "X_train = numpy.stack(X_train, axis=0)".

- A similar problem happend in function "def apply_model()", trying to call "predict_proba()", where I fixed it with "pred = model.predict_proba(numpy.array(D).reshape((1, 2)))"  

- In "apply_model()", when output folder is not existing, the line 
"with open(output_folder+os.sep+'answers.jsonl', 'w') as outfile:" leads to an error.

Best,
Benedikt

**Comment by mikekestemont** [comment]
Hi Benedikt, thanks for your very useful feedback! I respond below, but maybe you are willing to share your adaptations via a PR, since you seem to have implemented these already?

* Baseline "pan20-verif-baseline.py": Good point. I didn't run into this personally yet, but it makes sense to apply this.
* Baseline "pan20-authorship-verification-baseline-compressor.py": Here too, a PR would be great. I'm not sure we'll be able to accommodate the last suggestion, as we typically assume that such folders indeed already exist.
