### ISSUE TITLE
TwitterDownloader don't working

### ISSUE THREAD

**Issue by W-lw** [pan-webis-de/pan-code#3]
I use TwitterDownloader form pan15-author-profiling-twitter-downloader.zip to get pan16's data with command ``java -jar ./pan15-author-profiling-twitter-downloader/TwitterDownloader.jar --data ./pan16-author-profiling-training-dataset-english-2016-04-25 ``, which return ``ERROR java.lang.NullPointerException``.
Is its certification expired? Would you provide a new version of it?

**Comment by sarangshaikh2011** [comment]
I am also facing the same issue. 

Is there any solution?

**Comment by MattiWe** [comment]
So I don't think this downloader is going to work any longer due to the changes over at Twitter. 
We instead offer the pre-downloaded datasets over at zenodo (on request). (cf. https://pan.webis.de/data.html)

**Comment by nmiguezg** [comment]
Sorry, I would like to reopen this issue since I recently have been granted access to the PAN 2016 author profiling corpus (https://zenodo.org/record/3745963) but it doesn't actually contain the pre-downloaded datasets, at least for spanish the tags document where the tweets should have been are still empty.
I was interested in using this corpus in an academic work so I would like to know if you could upload the pre-download version of this dataset dataset (PAN 2016).
